# Generated by Django 5.1.4 on 2025-03-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_exchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='receiver_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_skill_exchanges', to='home.skill'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='sender_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_skill_exchanges', to='home.skill'),
        ),
    ]
