# Generated by Django 5.1.4 on 2025-03-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_exchangerequest_receiver_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='receiver_skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_skill_exchanges', to='home.skill'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='sender_skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_skill_exchanges', to='home.skill'),
        ),
    ]
