# Generated by Django 5.1.4 on 2025-03-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_exchangerequest_receiver_skill_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerequest',
            unique_together={('sender', 'receiver', 'sender_skill', 'receiver_skill')},
        ),
    ]
