# Generated by Django 5.1.4 on 2025-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_exchangerequest_status_chataccess_chatroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='4f1b8a2b8778', max_length=20, unique=True),
        ),
    ]
