# Generated by Django 5.1.4 on 2025-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_chatroom_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='f0abe5fa3a20', max_length=20, unique=True),
        ),
    ]
