# Generated by Django 5.1.4 on 2025-03-08 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSahyogProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('rank', models.CharField(choices=[('Beginner', 'Beginner'), ('Apprentice', 'Apprentice'), ('Skilled Mentor', 'Skilled Mentor'), ('Expert Guide', 'Expert Guide'), ('Master Connector', 'Master Connector')], default='Beginner', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
