# Generated by Django 5.1.4 on 2025-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_chatroom_room_id_alter_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='a8cde6fcee67', max_length=20, unique=True),
        ),
    ]
