# Generated by Django 5.1.4 on 2025-03-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_chatroom_room_id_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='8f4a970650a5', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='home.exchangerequest'),
        ),
    ]
