# Generated by Django 5.2 on 2025-04-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_contactmessage_alter_chatroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='96228a56bf59', max_length=20, unique=True),
        ),
    ]
