# Generated by Django 5.2 on 2025-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_chatroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='8b6553d4e925', max_length=20, unique=True),
        ),
    ]
